// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DraggableController from "./draggable_controller.js"
application.register("draggable", DraggableController)

import NavtabActiveController from "./navtab_active_controller.js"
application.register("navtab-active", NavtabActiveController)

import SearchRecipesController from "./search_recipes_controller.js"
application.register("search-recipes", SearchRecipesController)

import SelectThemeController from "./select_theme_controller.js"
application.register("select-theme", SelectThemeController)
