// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DraggableController from "./draggable_controller.js"
application.register("draggable", DraggableController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SearchRecipesController from "./search_recipes_controller.js"
application.register("search-recipes", SearchRecipesController)
